package com.example.androidassessment.presentation.breeds

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.core.view.isVisible
import androidx.core.widget.doAfterTextChanged
import androidx.fragment.app.Fragment
import androidx.fragment.app.viewModels
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.lifecycleScope
import androidx.lifecycle.repeatOnLifecycle
import androidx.recyclerview.widget.LinearLayoutManager
import com.example.androidassessment.R
import com.example.androidassessment.databinding.FragmentBreedsBinding
import com.example.androidassessment.domain.model.Breed
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.launch
import java.time.ZoneId
import java.time.format.DateTimeFormatter

@AndroidEntryPoint
class BreedsFragment : Fragment() {

    // ── View Binding ──────────────────────────────────────────────────────────

    private var _binding: FragmentBreedsBinding? = null
    private val binding get() = _binding!!

    // ── ViewModel + Adapter ───────────────────────────────────────────────────

    private val viewModel: BreedsViewModel by viewModels()
    private val breedAdapter = BreedAdapter()

    /** Snapshot of unfiltered breeds — held so the search can restore full list. */
    private var fullBreedList: List<Breed> = emptyList()

    private val timestampFormatter = DateTimeFormatter
        .ofPattern("HH:mm:ss")
        .withZone(ZoneId.systemDefault())

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        _binding = FragmentBreedsBinding.inflate(inflater, container, false)
        return binding.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        setupToolbar()
        setupRecyclerView()
        setupSearch()
        setupSwipeRefresh()
        setupErrorRetry()
        observeUiState()

        // Wire lifecycle-safe polling (ON_START → start, ON_STOP → stop)
        viewLifecycleOwner.lifecycle.addObserver(viewModel.lifecycleObserver)
    }

    override fun onDestroyView() {
        super.onDestroyView()
        _binding = null
    }

    // ── Setup ─────────────────────────────────────────────────────────────────

    private fun setupToolbar() {
        // Toolbar title already set in XML; add menu items here when needed
    }

    private fun setupRecyclerView() {
        binding.recyclerViewBreeds.apply {
            layoutManager = LinearLayoutManager(requireContext())
            adapter = breedAdapter
            setHasFixedSize(false)
        }
    }

    private fun setupSearch() {
        binding.editTextSearch.doAfterTextChanged { editable ->
            breedAdapter.filter(editable?.toString().orEmpty(), fullBreedList)
        }
    }

    private fun setupSwipeRefresh() {
        binding.swipeRefreshLayout.setOnRefreshListener {
            viewModel.refresh()
        }
    }

    private fun setupErrorRetry() {
        // errorLayout is a LayoutErrorBinding generated by ViewBinding
        binding.errorLayout.buttonRetry.setOnClickListener {
            viewModel.refresh()
        }
    }

    // ── State observation ─────────────────────────────────────────────────────

    private fun observeUiState() {
        viewLifecycleOwner.lifecycleScope.launch {
            viewLifecycleOwner.repeatOnLifecycle(Lifecycle.State.STARTED) {
                viewModel.uiState.collect { state ->
                    renderState(state)
                }
            }
        }
    }

    private fun renderState(state: BreedsUiState) {
        // ── Breeds list ────────────────────────────────────────────────────────
        if (state.breeds.isNotEmpty()) {
            fullBreedList = state.breeds
            val query = binding.editTextSearch.text?.toString().orEmpty()
            breedAdapter.filter(query, fullBreedList)
        }

        // ── Loading ────────────────────────────────────────────────────────────
        val showShimmer = state.isLoading && state.breeds.isEmpty()
        binding.shimmerLayout.isVisible = showShimmer
        binding.recyclerViewBreeds.isVisible = !showShimmer && state.error == null
        if (showShimmer) binding.shimmerLayout.startShimmer()
        else binding.shimmerLayout.stopShimmer()

        // SwipeRefresh spinner (only when already has data)
        binding.swipeRefreshLayout.isRefreshing = state.isLoading && state.breeds.isNotEmpty()

        // ── Error ──────────────────────────────────────────────────────────────
        val showError = state.error != null && state.breeds.isEmpty()
        binding.errorLayout.root.isVisible = showError
        if (showError) {
            binding.errorLayout.textViewErrorMessage.text = state.error
        }

        // ── Last updated ───────────────────────────────────────────────────────
        val lastUpdated = state.lastUpdated
        binding.textViewLastUpdated.isVisible = lastUpdated != null
        if (lastUpdated != null) {
            binding.textViewLastUpdated.text =
                getString(R.string.label_last_updated, timestampFormatter.format(lastUpdated))
        }
    }
}
